"""empty message

Revision ID: 085b2662a247
Revises: b8c0c4140a8d
Create Date: 2024-02-24 19:53:40.872901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '085b2662a247'
down_revision = 'b8c0c4140a8d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_line_address', sa.String(length=120), nullable=False),
    sa.Column('second_line_address', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('county', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_first_line_address'), ['first_line_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_second_line_address'), ['second_line_address'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_second_line_address'))
        batch_op.drop_index(batch_op.f('ix_customer_postal_code'))
        batch_op.drop_index(batch_op.f('ix_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_customer_last_name'))
        batch_op.drop_index(batch_op.f('ix_customer_first_name'))
        batch_op.drop_index(batch_op.f('ix_customer_first_line_address'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_county'))
        batch_op.drop_index(batch_op.f('ix_customer_city'))

    op.drop_table('customer')
    # ### end Alembic commands ###
