"""empty message

Revision ID: 23e90639b5ef
Revises: 9d1b2963234d
Create Date: 2024-03-11 19:20:47.781403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '23e90639b5ef'
down_revision = '9d1b2963234d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_job_completed_date')
        batch_op.drop_index('ix_job_job_created_date')
        batch_op.drop_index('ix_job_job_planned_date')
        batch_op.drop_column('job_completed_date')
        batch_op.drop_column('job_planned_date')
        batch_op.drop_column('job_created_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_created_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('job_planned_date', sa.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('job_completed_date', sa.DATETIME(), nullable=True))
        batch_op.create_index('ix_job_job_planned_date', ['job_planned_date'], unique=False)
        batch_op.create_index('ix_job_job_created_date', ['job_created_date'], unique=False)
        batch_op.create_index('ix_job_job_completed_date', ['job_completed_date'], unique=False)

    # ### end Alembic commands ###
