"""empty message

Revision ID: 3bffcdaf0c78
Revises: f4785a4f5b2a
Create Date: 2024-03-11 17:25:25.453877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bffcdaf0c78'
down_revision = 'f4785a4f5b2a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index('ix_invoice_iinvoice_due_date')
        batch_op.drop_index('ix_invoice_invoice_completed_date')
        batch_op.drop_index('ix_invoice_invoice_created_date')
        batch_op.drop_index('ix_invoice_invoice_notes')

    op.drop_table('invoice')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=False),
    sa.Column('customer_id', sa.INTEGER(), nullable=False),
    sa.Column('invoice_created_date', sa.DATETIME(), nullable=False),
    sa.Column('iinvoice_due_date', sa.DATETIME(), nullable=False),
    sa.Column('invoice_completed_date', sa.DATETIME(), nullable=False),
    sa.Column('invoice_cost', sa.FLOAT(), nullable=False),
    sa.Column('invoice_margin', sa.FLOAT(), nullable=False),
    sa.Column('invoice_price', sa.FLOAT(), nullable=False),
    sa.Column('invoice_notes', sa.VARCHAR(length=240), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index('ix_invoice_invoice_notes', ['invoice_notes'], unique=False)
        batch_op.create_index('ix_invoice_invoice_created_date', ['invoice_created_date'], unique=False)
        batch_op.create_index('ix_invoice_invoice_completed_date', ['invoice_completed_date'], unique=False)
        batch_op.create_index('ix_invoice_iinvoice_due_date', ['iinvoice_due_date'], unique=False)

    # ### end Alembic commands ###
