"""empty message

Revision ID: 6514c45491ed
Revises: 
Create Date: 2024-03-03 21:58:07.721714

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6514c45491ed'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(length=64), nullable=False),
    sa.Column('last_name', sa.String(length=64), nullable=False),
    sa.Column('phone', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('first_line_address', sa.String(length=120), nullable=False),
    sa.Column('second_line_address', sa.String(length=120), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=False),
    sa.Column('county', sa.String(length=120), nullable=False),
    sa.Column('postal_code', sa.String(length=120), nullable=False),
    sa.Column('referal', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_city'), ['city'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_county'), ['county'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_first_line_address'), ['first_line_address'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_first_name'), ['first_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_last_name'), ['last_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_postal_code'), ['postal_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_referal'), ['referal'], unique=False)
        batch_op.create_index(batch_op.f('ix_customer_second_line_address'), ['second_line_address'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('job_created_date', sa.DateTime(), nullable=False),
    sa.Column('job_planned_date', sa.DateTime(), nullable=False),
    sa.Column('job_completed_date', sa.DateTime(), nullable=False),
    sa.Column('job_status', sa.String(length=120), nullable=False),
    sa.Column('job_notes', sa.String(length=120), nullable=False),
    sa.Column('job_cost', sa.String(length=120), nullable=False),
    sa.Column('job_invoice', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_job_completed_date'), ['job_completed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_cost'), ['job_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_created_date'), ['job_created_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_invoice'), ['job_invoice'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_notes'), ['job_notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_planned_date'), ['job_planned_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_status'), ['job_status'], unique=False)

    op.create_table('job_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('item_created_date', sa.DateTime(), nullable=False),
    sa.Column('item_planned_date', sa.DateTime(), nullable=False),
    sa.Column('item_completed_date', sa.DateTime(), nullable=False),
    sa.Column('item_type', sa.String(length=120), nullable=False),
    sa.Column('item_description', sa.String(length=120), nullable=False),
    sa.Column('item_notes', sa.String(length=240), nullable=False),
    sa.Column('labour_hours', sa.Float(precision=120), nullable=False),
    sa.Column('item_cost', sa.Float(precision=120), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_item_item_completed_date'), ['item_completed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_item_cost'), ['item_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_item_created_date'), ['item_created_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_item_description'), ['item_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_item_notes'), ['item_notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_item_planned_date'), ['item_planned_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_labour_hours'), ['labour_hours'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_item_labour_hours'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_type'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_planned_date'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_notes'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_description'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_created_date'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_cost'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_completed_date'))

    op.drop_table('job_item')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_job_status'))
        batch_op.drop_index(batch_op.f('ix_job_job_planned_date'))
        batch_op.drop_index(batch_op.f('ix_job_job_notes'))
        batch_op.drop_index(batch_op.f('ix_job_job_invoice'))
        batch_op.drop_index(batch_op.f('ix_job_job_created_date'))
        batch_op.drop_index(batch_op.f('ix_job_job_cost'))
        batch_op.drop_index(batch_op.f('ix_job_job_completed_date'))

    op.drop_table('job')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_second_line_address'))
        batch_op.drop_index(batch_op.f('ix_customer_referal'))
        batch_op.drop_index(batch_op.f('ix_customer_postal_code'))
        batch_op.drop_index(batch_op.f('ix_customer_phone'))
        batch_op.drop_index(batch_op.f('ix_customer_last_name'))
        batch_op.drop_index(batch_op.f('ix_customer_first_name'))
        batch_op.drop_index(batch_op.f('ix_customer_first_line_address'))
        batch_op.drop_index(batch_op.f('ix_customer_email'))
        batch_op.drop_index(batch_op.f('ix_customer_county'))
        batch_op.drop_index(batch_op.f('ix_customer_city'))

    op.drop_table('customer')
    # ### end Alembic commands ###
