"""empty message

Revision ID: 91b1a4574396
Revises: e84ad22596ff
Create Date: 2024-03-10 19:51:23.892249

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91b1a4574396'
down_revision = 'e84ad22596ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.drop_index('ix_job_item_item_completed_date')
        batch_op.drop_index('ix_job_item_item_created_date')
        batch_op.drop_index('ix_job_item_item_planned_date')
        batch_op.drop_column('item_completed_date')
        batch_op.drop_column('item_created_date')
        batch_op.drop_column('item_planned_date')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_planned_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('item_created_date', sa.DATETIME(), nullable=False))
        batch_op.add_column(sa.Column('item_completed_date', sa.DATETIME(), nullable=False))
        batch_op.create_index('ix_job_item_item_planned_date', ['item_planned_date'], unique=False)
        batch_op.create_index('ix_job_item_item_created_date', ['item_created_date'], unique=False)
        batch_op.create_index('ix_job_item_item_completed_date', ['item_completed_date'], unique=False)

    # ### end Alembic commands ###
