"""empty message

Revision ID: 99e968b478a4
Revises: b02170b180e1
Create Date: 2024-03-17 21:29:33.192384

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '99e968b478a4'
down_revision = 'b02170b180e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_active', sa.Boolean(), nullable=True))

    with op.batch_alter_table('job_items', schema=None) as batch_op:
        batch_op.drop_index('ix_job_items_item_cost')
        batch_op.drop_index('ix_job_items_item_quantity')
        batch_op.drop_index('ix_job_items_item_total')
        batch_op.drop_column('item_total')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_total', sa.FLOAT(), nullable=True))
        batch_op.create_index('ix_job_items_item_total', ['item_total'], unique=False)
        batch_op.create_index('ix_job_items_item_quantity', ['item_quantity'], unique=False)
        batch_op.create_index('ix_job_items_item_cost', ['item_cost'], unique=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_column('customer_active')

    # ### end Alembic commands ###
