"""empty message

Revision ID: 9d1b2963234d
Revises: 3bffcdaf0c78
Create Date: 2024-03-11 19:18:03.603827

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9d1b2963234d'
down_revision = '3bffcdaf0c78'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.drop_index('ix_job_item_item_cost')
        batch_op.drop_index('ix_job_item_item_description')
        batch_op.drop_index('ix_job_item_item_notes')
        batch_op.drop_index('ix_job_item_item_quantity')
        batch_op.drop_index('ix_job_item_item_type')
        batch_op.drop_index('ix_job_item_labour_hours')

    op.drop_table('job_item')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('job_id', sa.INTEGER(), nullable=True),
    sa.Column('item_type', sa.VARCHAR(length=120), nullable=True),
    sa.Column('item_description', sa.VARCHAR(length=120), nullable=True),
    sa.Column('item_notes', sa.VARCHAR(length=240), nullable=True),
    sa.Column('labour_hours', sa.FLOAT(), nullable=True),
    sa.Column('item_cost', sa.FLOAT(), nullable=True),
    sa.Column('item_quantity', sa.FLOAT(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.create_index('ix_job_item_labour_hours', ['labour_hours'], unique=False)
        batch_op.create_index('ix_job_item_item_type', ['item_type'], unique=False)
        batch_op.create_index('ix_job_item_item_quantity', ['item_quantity'], unique=False)
        batch_op.create_index('ix_job_item_item_notes', ['item_notes'], unique=False)
        batch_op.create_index('ix_job_item_item_description', ['item_description'], unique=False)
        batch_op.create_index('ix_job_item_item_cost', ['item_cost'], unique=False)

    # ### end Alembic commands ###
