"""empty message

Revision ID: 9f13fbb4992c
Revises: 99e968b478a4
Create Date: 2024-03-20 19:48:30.456731

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f13fbb4992c'
down_revision = '99e968b478a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_created_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('job_planned_date', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('job_completed_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('job_notes',
               existing_type=sa.VARCHAR(length=240),
               type_=sa.Text(length=240),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('job_notes',
               existing_type=sa.Text(length=240),
               type_=sa.VARCHAR(length=240),
               existing_nullable=True)
        batch_op.drop_column('job_completed_date')
        batch_op.drop_column('job_planned_date')
        batch_op.drop_column('job_created_date')

    # ### end Alembic commands ###
