"""empty message

Revision ID: a23704077f45
Revises: ce80c2c485e6
Create Date: 2024-02-26 21:44:21.186871

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a23704077f45'
down_revision = 'ce80c2c485e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('job_type', sa.String(length=120), nullable=False),
    sa.Column('job_description', sa.String(length=120), nullable=False),
    sa.Column('job_date', sa.DateTime(), nullable=False),
    sa.Column('job_status', sa.String(length=120), nullable=False),
    sa.Column('job_notes', sa.String(length=120), nullable=False),
    sa.Column('job_cost', sa.String(length=120), nullable=False),
    sa.Column('job_invoice', sa.String(length=120), nullable=False),
    sa.Column('job_invoice_date', sa.String(length=120), nullable=False),
    sa.Column('job_invoice_paid', sa.Boolean(create_constraint=120), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_job_cost'), ['job_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_date'), ['job_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_description'), ['job_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_invoice'), ['job_invoice'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_invoice_date'), ['job_invoice_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_invoice_paid'), ['job_invoice_paid'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_notes'), ['job_notes'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_status'), ['job_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_job_type'), ['job_type'], unique=False)

    op.create_table('job_item',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('item_type', sa.String(length=120), nullable=False),
    sa.Column('item_description', sa.String(length=120), nullable=False),
    sa.Column('item_cost', sa.String(length=120), nullable=False),
    sa.Column('labour_hours', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_item_item_cost'), ['item_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_item_description'), ['item_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_item_type'), ['item_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_item_labour_hours'), ['labour_hours'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_item_labour_hours'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_type'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_description'))
        batch_op.drop_index(batch_op.f('ix_job_item_item_cost'))

    op.drop_table('job_item')
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_job_type'))
        batch_op.drop_index(batch_op.f('ix_job_job_status'))
        batch_op.drop_index(batch_op.f('ix_job_job_notes'))
        batch_op.drop_index(batch_op.f('ix_job_job_invoice_paid'))
        batch_op.drop_index(batch_op.f('ix_job_job_invoice_date'))
        batch_op.drop_index(batch_op.f('ix_job_job_invoice'))
        batch_op.drop_index(batch_op.f('ix_job_job_description'))
        batch_op.drop_index(batch_op.f('ix_job_job_date'))
        batch_op.drop_index(batch_op.f('ix_job_job_cost'))

    op.drop_table('job')
    # ### end Alembic commands ###
