"""empty message

Revision ID: b02170b180e1
Revises: e127c951e6d2
Create Date: 2024-03-12 20:22:54.770859

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b02170b180e1'
down_revision = 'e127c951e6d2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('job_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=True),
    sa.Column('item_name', sa.String(length=120), nullable=True),
    sa.Column('item_description', sa.String(length=240), nullable=True),
    sa.Column('item_cost', sa.Float(), nullable=True),
    sa.Column('item_quantity', sa.Integer(), nullable=True),
    sa.Column('item_total', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('job_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_items_item_cost'), ['item_cost'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_items_item_description'), ['item_description'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_items_item_name'), ['item_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_items_item_quantity'), ['item_quantity'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_items_item_total'), ['item_total'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_items_item_total'))
        batch_op.drop_index(batch_op.f('ix_job_items_item_quantity'))
        batch_op.drop_index(batch_op.f('ix_job_items_item_name'))
        batch_op.drop_index(batch_op.f('ix_job_items_item_description'))
        batch_op.drop_index(batch_op.f('ix_job_items_item_cost'))

    op.drop_table('job_items')
    # ### end Alembic commands ###
