"""empty message

Revision ID: bb5d129a680f
Revises: c4891c241c92
Create Date: 2024-03-04 21:37:18.942315

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bb5d129a680f'
down_revision = 'c4891c241c92'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('invoice',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('invoice_created_date', sa.DateTime(), nullable=False),
    sa.Column('iinvoice_due_date', sa.DateTime(), nullable=False),
    sa.Column('invoice_completed_date', sa.DateTime(), nullable=False),
    sa.Column('invoice_cost', sa.Float(), nullable=False),
    sa.Column('invoice_margin', sa.Float(), nullable=False),
    sa.Column('invoice_price', sa.Float(), nullable=False),
    sa.Column('invoice_notes', sa.String(length=240), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_invoice_iinvoice_due_date'), ['iinvoice_due_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_completed_date'), ['invoice_completed_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_created_date'), ['invoice_created_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_invoice_invoice_notes'), ['invoice_notes'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invoice', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_notes'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_created_date'))
        batch_op.drop_index(batch_op.f('ix_invoice_invoice_completed_date'))
        batch_op.drop_index(batch_op.f('ix_invoice_iinvoice_due_date'))

    op.drop_table('invoice')
    # ### end Alembic commands ###
