"""empty message

Revision ID: c4891c241c92
Revises: 6514c45491ed
Create Date: 2024-03-03 22:00:53.701897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4891c241c92'
down_revision = '6514c45491ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index('ix_job_job_cost')
        batch_op.drop_column('job_cost')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_cost', sa.VARCHAR(length=120), nullable=False))
        batch_op.create_index('ix_job_job_cost', ['job_cost'], unique=False)

    # ### end Alembic commands ###
