"""empty message

Revision ID: ce80c2c485e6
Revises: 085b2662a247
Create Date: 2024-02-24 20:17:13.333615

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce80c2c485e6'
down_revision = '085b2662a247'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.add_column(sa.Column('referal', sa.String(length=120), nullable=False))
        batch_op.create_index(batch_op.f('ix_customer_referal'), ['referal'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_referal'))
        batch_op.drop_column('referal')

    # ### end Alembic commands ###
