"""empty message

Revision ID: e127c951e6d2
Revises: f284b1151d73
Create Date: 2024-03-11 20:46:15.603925

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e127c951e6d2'
down_revision = 'f284b1151d73'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_type', sa.String(length=120), nullable=True))
        batch_op.create_index(batch_op.f('ix_job_job_type'), ['job_type'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_job_type'))
        batch_op.drop_column('job_type')

    # ### end Alembic commands ###
