"""empty message

Revision ID: f284b1151d73
Revises: 23e90639b5ef
Create Date: 2024-03-11 20:37:20.113986

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f284b1151d73'
down_revision = '23e90639b5ef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('invoice_status', sa.String(length=120), nullable=True))
        batch_op.alter_column('job_notes',
               existing_type=sa.VARCHAR(length=120),
               type_=sa.String(length=240),
               existing_nullable=True)
        batch_op.drop_index('ix_job_job_invoice')
        batch_op.create_index(batch_op.f('ix_job_invoice_status'), ['invoice_status'], unique=False)
        batch_op.drop_column('job_invoice')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('job_invoice', sa.VARCHAR(length=120), nullable=True))
        batch_op.drop_index(batch_op.f('ix_job_invoice_status'))
        batch_op.create_index('ix_job_job_invoice', ['job_invoice'], unique=False)
        batch_op.alter_column('job_notes',
               existing_type=sa.String(length=240),
               type_=sa.VARCHAR(length=120),
               existing_nullable=True)
        batch_op.drop_column('invoice_status')

    # ### end Alembic commands ###
