"""empty message

Revision ID: f4785a4f5b2a
Revises: 91b1a4574396
Create Date: 2024-03-11 17:22:13.057086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4785a4f5b2a'
down_revision = '91b1a4574396'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('first_line_address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('second_line_address',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('referal',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('job_created_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('job_planned_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('job_completed_date',
               existing_type=sa.DATETIME(),
               nullable=True)
        batch_op.alter_column('job_status',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('job_notes',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('job_invoice',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('item_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('item_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)
        batch_op.alter_column('item_notes',
               existing_type=sa.VARCHAR(length=240),
               nullable=True)
        batch_op.alter_column('labour_hours',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('item_cost',
               existing_type=sa.FLOAT(),
               nullable=True)
        batch_op.alter_column('item_quantity',
               existing_type=sa.FLOAT(),
               nullable=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=True)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    with op.batch_alter_table('job_item', schema=None) as batch_op:
        batch_op.alter_column('item_quantity',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('item_cost',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('labour_hours',
               existing_type=sa.FLOAT(),
               nullable=False)
        batch_op.alter_column('item_notes',
               existing_type=sa.VARCHAR(length=240),
               nullable=False)
        batch_op.alter_column('item_description',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('item_type',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('job_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.alter_column('job_invoice',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('job_notes',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('job_status',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('job_completed_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('job_planned_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('job_created_date',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('customer_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.alter_column('referal',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('postal_code',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('county',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('city',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('second_line_address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('first_line_address',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('email',
               existing_type=sa.VARCHAR(length=120),
               nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('last_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)
        batch_op.alter_column('first_name',
               existing_type=sa.VARCHAR(length=64),
               nullable=False)

    # ### end Alembic commands ###
